### ISSUE TITLE
Uniform Testing 4 March 2016

### ISSUE THREAD

**Issue by Annette-FSN** [FsN/FsN_Internal#10]
**Request for Testing:**

<img width="913" alt="screen shot 2016-03-04 at 9 12 08 am" src="https://cloud.githubusercontent.com/assets/2699568/13520386/9602f402-e1e8-11e5-8dc5-e819e50fb54a.png">

**Comment by Annette-FSN** [comment]
From the team:
Thank you, the test orders are completed. 
We could not find the second employee code that he requested the test be done on so 
We placed one on a different employee in the same account as the first one

if the employee is not in our database it means that it is not in the educos push
so possibly  either typed the employee number wrong or possibly  looking at employees that are not in the push data

**Comment by Annette-FSN** [comment]
I placed 1 order into loan amount for 0002041697 and GRVd it.

Employee 0002037628 is not in our database so it is not in the educos push data. I placed an order on 0002066724 instead.

1. 
![3db8bf2c-e1e6-11e5-825f-c42076da5a9f](https://cloud.githubusercontent.com/assets/2699568/13520436/e8e41052-e1e8-11e5-82a1-4c6dfb194c1f.png)

2.
![1d21ab20-e1e6-11e5-9e18-2dad76c65120](https://cloud.githubusercontent.com/assets/2699568/13520438/f199d3b2-e1e8-11e5-9680-68434b7c5ca9.png)

**Comment by fsn-mandy** [comment]
<img width="1089" alt="screen shot 2016-03-16 at 10 10 14" src="https://cloud.githubusercontent.com/assets/2392195/13891077/b1bba5a2-ed57-11e5-8115-dcf9730ff025.png">

**Comment by fsn-mandy** [comment]
<img width="693" alt="screen shot 2016-03-18 at 22 23 57" src="https://cloud.githubusercontent.com/assets/2392195/13891132/fcfa4118-ed57-11e5-9b59-7b3b3f377527.png">


<img width="693" alt="screen shot 2016-03-18 at 22 23 57" src="https://cloud.githubusercontent.com/assets/2392195/13891167/2aa5792a-ed58-11e5-9cb7-f3f4625df975.png">
